logger:
    file: /open5gs/install/var/log/open5gs/upf.log

parameter:

upf:
    pfcp:
      - addr: UPF_IP
    gtpu:
      - addr: UPF_IP
        advertise: UPF_ADVERTISE_IP
    subnet:
      - addr: 10.45.0.1/16
      # - addr: 2001:db8:cafe::1/48
    metrics:
      - addr: UPF_IP
        port: 9091

smf:
    pfcp:
      - addr: SMF_IP
