version: '3'

volumes:
  mongodb: {}

#Setting up the common range of ips used by all the containers (5g services and webui)
networks:
  common_network:
    ipam:
      config:
       - subnet: ${COMMON_NETWORK}

services:
  mongo:
    image: ${MONGO_IMAGE}
    container_name: mongodb
    env_file:
      - .env
    volumes:
      - mongodb:/var/lib/mongodb
      - ./mongo:/mnt/mongo
    expose:
      - "27017/udp"
      - "27017/tcp"
    networks:
      common_network:
        ipv4_address: ${MONGO_IP}

  webui:
    image: ${OPEN5GS_IMAGE}
    container_name: webui
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=webui
    volumes:
      - ./webui:/mnt/webui
    ports:
      - "3000:3000/tcp"
    networks:
      common_network:
        ipv4_address: ${WEBUI_IP}
  nrf:
    image: ${OPEN5GS_IMAGE}
    container_name: nrf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=nrf-1
    volumes:
      - ./open5gs/config/nrf:/mnt/nrf
      - ./log:/open5gs/install/var/log/open5gs
    expose:
      - "7777/tcp"
    networks:
      common_network:
        ipv4_address: ${NRF_IP}
  scp:
    image: ${OPEN5GS_IMAGE}
    container_name: scp
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=scp-1
    volumes:
      - ./open5gs/config/scp:/mnt/scp
      - ./log:/open5gs/install/var/log/open5gs
    expose:
      - "7777/tcp"
    networks:
      common_network:
        ipv4_address: ${SCP_IP}
  ausf:
    image: ${OPEN5GS_IMAGE}
    depends_on:
      - nrf
      - scp
    container_name: ausf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=ausf-1
    volumes:
      - ./open5gs/config/ausf:/mnt/ausf
      - ./log:/open5gs/install/var/log/open5gs
    expose:
      - "7777/tcp"
    networks:
      common_network:
        ipv4_address: ${AUSF_IP}
  udr:
    image: ${OPEN5GS_IMAGE}
    depends_on:
      - nrf
      - scp
      - mongo
    container_name: udr
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=udr-1
    volumes:
      - ./open5gs/config/udr:/mnt/udr
      - ./log:/open5gs/install/var/log/open5gs
    expose:
      - "7777/tcp"
    networks:
      common_network:
        ipv4_address: ${UDR_IP}
  udm:
    image: ${OPEN5GS_IMAGE}
    depends_on:
      - nrf
      - scp
    container_name: udm
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=udm-1
    volumes:
      - ./open5gs/config/udm:/mnt/udm
      - ./log:/open5gs/install/var/log/open5gs
    expose:
      - "7777/tcp"
    networks:
      common_network:
        ipv4_address: ${UDM_IP}
  pcf:
    image: ${OPEN5GS_IMAGE}
    depends_on:
      - nrf
      - scp
      - mongo
    container_name: pcf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=pcf-1
    volumes:
      - ./open5gs/config/pcf:/mnt/pcf
      - ./log:/open5gs/install/var/log/open5gs
    expose:
      - "7777/tcp"
      - "9091/tcp"
    networks:
      common_network:
        ipv4_address: ${PCF_IP}
  bsf:
    image: ${OPEN5GS_IMAGE}
    depends_on:
      - nrf
      - scp
      - mongo
    container_name: bsf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=bsf-1
    volumes:
      - ./open5gs/config/bsf:/mnt/bsf
      - ./log:/open5gs/install/var/log/open5gs
    expose:
      - "7777/tcp"
    networks:
      common_network:
        ipv4_address: ${BSF_IP}
  nssf:
    image: ${OPEN5GS_IMAGE}
    depends_on:
      - nrf
      - scp
      - mongo
    container_name: nssf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=nssf-1
    volumes:
      - ./open5gs/config/nssf:/mnt/nssf
      - ./log:/open5gs/install/var/log/open5gs
    expose:
      - "7777/tcp"
    networks:
      common_network:
        ipv4_address: ${NSSF_IP}

  smf:
    image: ${OPEN5GS_IMAGE}
    depends_on:
      - nrf
      - scp
      - amf
    container_name: smf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=smf-1
    volumes:
      - ./open5gs/config/smf:/mnt/smf
      - ./log:/open5gs/install/var/log/open5gs
    expose:
      - "3868/udp"
      - "3868/tcp"
      - "3868/sctp"
      - "5868/udp"
      - "5868/tcp"
      - "5868/sctp"
      - "8805/udp"
      - "2123/udp"
      - "7777/tcp"
      - "9091/tcp"
    networks:
      common_network:
        ipv4_address: ${SMF_IP}
  upf:
    image: ${OPEN5GS_IMAGE}
    depends_on:
      - nrf
      - scp
      - smf
    container_name: upf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=upf-1
    volumes:
      - ./open5gs/config/upf:/mnt/upf
      - ./log:/open5gs/install/var/log/open5gs
    expose:
      - "2152/udp"
      - "8805/udp"
      - "9091/tcp"
    # ports:
    #   - "2152:2152/udp"
    cap_add:
      - NET_ADMIN
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1
      #- net.ipv6.conf.all.disable_ipv6=0
    networks:
      common_network:
        ipv4_address: ${UPF_IP}
  amf:
    image: ${OPEN5GS_IMAGE}
    depends_on:
      - nrf
      - scp
      - ausf
      - udm
      - udr
      - pcf
      - bsf
    container_name: amf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=amf-1
    volumes:
      - ./open5gs/config/amf:/mnt/amf
      - ./log:/open5gs/install/var/log/open5gs
    expose:
      - "38412/sctp"
      - "7777/tcp"
      - "9091/tcp"
    # ports:
    #   - "38412:38412/sctp"
    networks:
      common_network:
        ipv4_address: ${AMF_IP}

  nr_gnb:
    image: ${UERANSIM_IMAGE}
    container_name: nr_gnb
    depends_on:
      - amf
    stdin_open: true
    tty: true
    volumes:
      - ./ueransim:/mnt/ueransim
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=ueransim-gnb-1
    expose:
      - "38412/sctp"
      - "2152/udp"
      - "4997/udp"
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      common_network:
        ipv4_address: ${NR_GNB_IP}

  nr_ue:
    image: ${UERANSIM_IMAGE}
    container_name: nr_ue
    depends_on:
      - nr_gnb
    stdin_open: true
    tty: true
    volumes:
      - ./ueransim:/mnt/ueransim
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=ueransim-ue-1
    expose:
      - "4997/udp"
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      common_network:
        ipv4_address: ${NR_UE_IP}